### ISSUE TITLE
Version: 0.20.0 Check for updates yields unhandled exception

### ISSUE THREAD

**Issue by rkresha** [mirinsoft/sharpapp#3]
![image](https://user-images.githubusercontent.com/19247761/80163213-119abc80-859b-11ea-9e60-53fe4b0063ab.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Single.Parse(String s)
   at SharpApp.Main.CheckForUpdates()
   at SharpApp.Main.UpdateCheck_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SharpApp
    Assembly Version: 0.20.0.0
    Win32 Version: 0.20.0.0
    CodeBase: file:///C:/Users/USERNAME/Qsync/SharpApp/SharpApp.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

**Comment by Belim** [comment]
I can not recreate this bug :O 
How often did you tried? Also from a different machine?

**Comment by rkresha** [comment]
I've tried several times on the same machine.

**Comment by rkresha** [comment]
Confirmed does the same thing on another PC.

**Comment by Belim** [comment]
Thanks, please try the again with the latest build
https://github.com/mirinsoft/sharpapp/releases/tag/0.21.1

**Comment by lst97** [comment]
Error confirmed when using **0.30.0.0**
OS version:
Major  Minor  Build  Revision
-----    -----    -----    --------
10        0         18363      0

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Single.Parse(String s)
   at SharpApp.Main.CheckForUpdates()
   at SharpApp.Main.UpdateCheck_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SharpApp
    Assembly Version: 0.30.0.0
    Win32 Version: 0.30.0.0
    CodeBase: file:///C:/Users/Administrator/Desktop/Debotnet/_ShareApp/SharpApp.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by rkresha** [comment]
0.32 yields
![image](https://user-images.githubusercontent.com/19247761/80925030-338dff00-8d52-11ea-8baf-87efabdc58d2.png)

**Comment by Belim** [comment]
Damn, it's hard to debug as it's invisible to me :(
Please try latest build 0.32.1 I've changed also one variable regarding the update ;)

**Comment by lst97** [comment]
> 
> 
> 0.32 yields
> ![image](https://user-images.githubusercontent.com/19247761/80925030-338dff00-8d52-11ea-8baf-87efabdc58d2.png)

Same Error with **0.32.1** 
However without internet connection, the exception won't appear.
 
![without_internet](https://user-images.githubusercontent.com/16495912/80970818-201c8a00-8e5f-11ea-9556-11e30c29e838.png)

Hope this help.

**Comment by Belim** [comment]
What does the latest build say?

**Comment by lst97** [comment]
As I always encounter this issue, I will update the information here for each build about this error, until it fix. 

![Untitled](https://user-images.githubusercontent.com/16495912/81377799-8d733800-9149-11ea-8aff-5985c1789f96.png)

Tested Build: _0.34.0 (Achilles)_

**Comment by Belim** [comment]
Please click in build 0.34.1 at the yellow version badge in the lower left corner and tell me whether the right version is shown

**Comment by lst97** [comment]
The correct version was show. However the check update still failed.

> 
> ![Untitled](https://user-images.githubusercontent.com/16495912/81377799-8d733800-9149-11ea-8aff-5985c1789f96.png)
> 
> Tested Build: _0.34.0 (Achilles)_

![Untitled](https://user-images.githubusercontent.com/16495912/81474077-76fed680-9246-11ea-8b45-6b2d67755992.png)

Tested Build: _0.34.1 (Achilles)_

**Comment by lst97** [comment]
The yellow label check version button works fine.
![Uploading update check_coner.png…]()

The ... > Check For Updates, check update fail.

Tested Build: _0.34.2 (Achilles)_

**Comment by Belim** [comment]
Thanks for the continuous feedback.
Can you please test this build
[SharpApp.zip](https://github.com/mirinsoft/sharpapp/files/4620689/SharpApp.zip)

**Comment by lst97** [comment]
![Untitled](https://user-images.githubusercontent.com/16495912/81801930-83da3d80-9558-11ea-9c3f-78010beb2a99.png)

Tested Build: 0.34.3 (unofficial)

**Comment by Belim** [comment]
👌 then we finally made it, thanks.

**Comment by lst97** [comment]
> 👌 then we finally made it, thanks.

Will you make it like Debonet, which will download the latest version without opening the browser?

**Comment by Belim** [comment]
> > 👌 then we finally made it, thanks.
> 
> Will you make it like Debonet, which will download the latest version without opening the browser?

Would be no problem, but i think the current solution is better because you have the release notes in front of you. There are two clicks more. I'll see if there's any more feedback for an solution like Debotnet or maybe "auto. updater" < I personally am not a fan of these and prefer the manual way

**Comment by Belim** [comment]
Finally fixed here https://github.com/mirinsoft/sharpapp/releases/tag/0.34.4
